name = "gardener-bot"
main = "src/index.js"
compatibility_date = "2024-01-15"

[env.production.vars]
# These will be set in Cloudflare dashboard
BOT_TOKEN = ""
TELEGRAM_CHAT_ID = ""

[[env.production.triggers]]
crons = ["15 8 * * *", "15 16 * * *"]