name = "gardener-bot"
main = "src/index.js"
compatibility_date = "2024-01-15"

[env.production.vars]
# These will be set in Cloudflare dashboard
BOT_TOKEN = "7695891707:AAFv4K6WtkjHeu9B3ZHlc9GBUPMz748pnYo"
TELEGRAM_CHAT_ID = "-1002724251424"

