name: Gardener Bot Cron

on:
  schedule:
    # Morning reminder: 8:15 AM Cambodia (1:15 AM UTC)
    - cron: '15 1 * * 1-6'  # Monday to Saturday
    # Evening reminder: 4:15 PM Cambodia (9:15 AM UTC)  
    - cron: '15 9 * * 1-6'  # Monday to Saturday
  
  # Allow manual trigger for testing
  workflow_dispatch:
    inputs:
      reminder_type:
        description: 'Type of reminder to send'
        required: true
        default: 'morning'
        type: choice
        options:
        - morning
        - evening

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    
    steps:
    - name: Send Morning Reminder
      if: github.event.schedule == '15 1 * * 1-6' || (github.event_name == 'workflow_dispatch' && github.event.inputs.reminder_type == 'morning')
      run: |
        curl -X GET "https://gardener-bot.ingchina2004.workers.dev/morning"
        
    - name: Send Evening Reminder  
      if: github.event.schedule == '15 9 * * 1-6' || (github.event_name == 'workflow_dispatch' && github.event.inputs.reminder_type == 'evening')
      run: |
        curl -X GET "https://gardener-bot.ingchina2004.workers.dev/evening"
        
    - name: Log Execution
      run: |
        echo "Gardener Bot cron executed at $(date)"
        echo "Event: ${{ github.event_name }}"
        echo "Schedule: ${{ github.event.schedule }}"